using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Datadog.Maui.Extensions;

namespace DatadogMauiSample;

/// <summary>
/// Entry point for the MAUI application configuration.
/// </summary>
public static class MauiProgram
{
	/// <summary>
	/// Creates and configures the MAUI application.
	/// </summary>
	/// <returns>The configured <see cref="MauiApp"/>.</returns>
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();

		// Load configuration from appsettings.json
		LoadAppSettings(builder);

		builder
			// Configure Datadog BEFORE UseMauiApp to ensure SDK is initialized early
			.UseDatadogFromConfiguration(configureRum: rum =>
			{
				// Programmatically set Variant and BuildId for crash symbolication
				// These are auto-generated by the Datadog.MAUI.Symbols package
				rum.Variant = Datadog.MAUI.Symbols.DatadogBuildInfo.Variant;
				rum.BuildId = Datadog.MAUI.Symbols.DatadogBuildInfo.BuildId;
			})
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			})
			.ConfigureMauiHandlers(handlers =>
			{
#if ANDROID
				// Register custom WebView handler for Android to enable Datadog tracking
				handlers.AddHandler<WebView, Platforms.Android.DatadogWebViewHandler>();
#endif
			});

#if DEBUG
		builder.Logging.AddDebug();
#endif

		return builder.Build();
	}

	/// <summary>
	/// Loads appsettings.json into the builder configuration.
	/// Supports optional appsettings.Development.json override.
	/// </summary>
	private static void LoadAppSettings(MauiAppBuilder builder)
	{
		var configBuilder = new ConfigurationBuilder();

		try
		{
			// Load base configuration
			var baseMemoryStream = new MemoryStream();
			using (var baseStream = FileSystem.OpenAppPackageFileAsync("appsettings.json").GetAwaiter().GetResult())
			{
				baseStream.CopyTo(baseMemoryStream);
				baseMemoryStream.Position = 0;
			}
			configBuilder.AddJsonStream(baseMemoryStream);

			// Try to load development override (optional)
			try
			{
				var devMemoryStream = new MemoryStream();
				using (var devStream = FileSystem.OpenAppPackageFileAsync("appsettings.Development.json").GetAwaiter().GetResult())
				{
					devStream.CopyTo(devMemoryStream);
					devMemoryStream.Position = 0;
				}
				configBuilder.AddJsonStream(devMemoryStream);
			}
			catch (FileNotFoundException)
			{
				// Development config is optional - silently continue
			}

			var config = configBuilder.Build();
			builder.Configuration.AddConfiguration(config);
		}
		catch (Exception ex)
		{
			System.Diagnostics.Debug.WriteLine($"[Config] ERROR loading appsettings.json: {ex.Message}");
		}
	}
}
